2025-04-05 20:02:23,617 ERROR: Exception on /match/1 [GET] [in C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\sql\coercions.py", line 803, in _literal_coercion
    return expr._bind_param(operator, element, type_=bindparam_type)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 4617, in _bind_param
    return BindParameter(
        self.key,
    ...<5 lines>...
        expanding=expanding,
    )
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 2043, in __init__
    self.type = _compared_to_type.coerce_compared_value(
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        _compared_to_operator, check_value
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\sql\type_api.py", line 1059, in coerce_compared_value
    _coerced_type = _resolve_value_to_type(value)
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\sql\sqltypes.py", line 3825, in _resolve_value_to_type
    raise exc.ArgumentError(
        "Object %r is not legal as a SQL literal value" % (value,)
    )
sqlalchemy.exc.ArgumentError: Object <Match location1 2025-04-05 14:55:06.587725> is not legal as a SQL literal value

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\app\routes.py", line 135, in match
    .where(Score.match_id == id)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\sql\operators.py", line 584, in __eq__
    return self.operate(eq, other)
           ~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\orm\attributes.py", line 453, in operate
    return op(self.comparator, *other, **kwargs)  # type: ignore[no-any-return]  # noqa: E501
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\sql\operators.py", line 584, in __eq__
    return self.operate(eq, other)
           ~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\orm\properties.py", line 477, in operate
    return op(self.__clause_element__(), *other, **kwargs)  # type: ignore[no-any-return]  # noqa: E501
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\sql\annotation.py", line 371, in __eq__
    return self.__element.__class__.__eq__(self, other)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\sql\operators.py", line 584, in __eq__
    return self.operate(eq, other)
           ~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 1523, in operate
    return op(self.comparator, *other, **kwargs)  # type: ignore[no-any-return]  # noqa: E501
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\sql\operators.py", line 584, in __eq__
    return self.operate(eq, other)
           ~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\sql\type_api.py", line 212, in operate
    return op_fn(self.expr, op, *other, **addtl_kw)
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\sql\default_comparator.py", line 121, in _boolean_compare
    obj = coercions.expect(
        roles.BinaryElementRole, element=obj, operator=op, expr=expr
    )
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\sql\coercions.py", line 395, in expect
    resolved = impl._literal_coercion(
        element, argname=argname, **kw
    )
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\sql\coercions.py", line 805, in _literal_coercion
    self._raise_for_expected(element, err=err)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\sql\coercions.py", line 784, in _raise_for_expected
    return super()._raise_for_expected(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        element, argname=argname, resolved=resolved, advice=advice, **kw
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\venv\Lib\site-packages\sqlalchemy\sql\coercions.py", line 518, in _raise_for_expected
    raise exc.ArgumentError(msg, code=code) from err
sqlalchemy.exc.ArgumentError: SQL expression element or literal value expected, got <Match location1 2025-04-05 14:55:06.587725>.
2025-04-05 20:07:27,276 INFO: Skylog startup [in C:\Users\tenni\OneDrive\Documents\python\NEA-Project\skylog\app\__init__.py:37]
